### ISSUE TITLE
test for compatibility with the overflow menu before treating an extension as featured

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/featured-addons-compatibility-test#1]
For example: 

[Not compatible with the Australis menu · Issue #13 · james-fray/tab-reloader](https://github.com/james-fray/tab-reloader/issues/13)

The next extension that I installed was amongst the shortlist of six featured extensions at https://addons.mozilla.org/en-GB/firefox/ … this, too, is a poor fit for Australis and overflow menus: 

![screenshot_20170813_214318](https://user-images.githubusercontent.com/192271/29253296-8390f5bc-8070-11e7-9992-1dbc9e1d9745.png)

![screenshot_20170813_215158](https://user-images.githubusercontent.com/192271/29253340-b06949ee-8071-11e7-8eed-2c95446ccd3f.png)

**Comment by wagnerand** [comment]
This repository was being used for compatibility tests around 48. It hasn't been used after that. 

I see you are running Nightly. It is up to add-on developers to make their add-on compatible to Nightly, but for *featured* status, we only require it to work on the release version.
